 name: Desktop Build

on:
  push:
    branches: [ moim-features ]
    paths:
      - 'desktop/**'
      - 'core/**'
      - '.github/workflows/desktop-build.yml'
  pull_request:
    branches: [ moim-features ]
    paths:
      - 'desktop/**'
      - 'core/**'
      - '.github/workflows/desktop-build.yml'
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build core
        run: yarn workspace livemock-core build

      - name: Build desktop app
        run: yarn workspace livemock build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List release directory
        run: find desktop/release -type f -name "*.dmg"

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mac-build
          path: desktop/release/**/*.dmg
          if-no-files-found: warn

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build core
        run: yarn workspace livemock-core build

      - name: Build desktop app
        run: yarn workspace livemock build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List release directory
        run: dir desktop\release /s /b | findstr ".exe"
        shell: cmd

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: desktop/release/**/*.exe
          if-no-files-found: warn

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Build core
        run: yarn workspace livemock-core build

      - name: Build desktop app
        run: yarn workspace livemock build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List release directory
        run: find desktop/release -type f -name "*.AppImage" -o -name "*.deb"

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: |
            desktop/release/**/*.AppImage
            desktop/release/**/*.deb
          if-no-files-found: warn